routes/web.php
<?php
  use App\Http\Controllers\LanguageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('auth/google', 'Auth\GoogleController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\GoogleController@handleGoogleCallback');

// Route url
Route::get('/', 'DashboardController@dashboardAnalytics')->name('home')->middleware('auth');
Route::get('/home', 'DashboardController@dashboardAnalytics')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
  // Route Dashboards
  Route::get('/dashboard-analytics', 'DashboardController@dashboardAnalytics');

  // Content resources
  Route::get('/soumissions', 'QuotesController@list');
  Route::get('/soumissions/create', 'QuotesController@create')->name('quotes.create');
  Route::get('/soumissions/{id}/edit', 'QuotesController@edit')->name('quotes.edit');
  Route::get('/soumissions/{id}/delete', 'QuotesController@destroy')->name('quotes.destroy');
  Route::resource('clients','ClientsController');
  Route::resource('employes','EmployesController');

  // Order resources
  Route::get('/commandes', 'OrdersController@index');
  Route::get('/commandes/{order}/edit', 'OrdersController@edit')->name('orders.edit');
  Route::get('/commandes/{order}/delete', 'OrdersController@destroy')->name('orders.destroy');
});

// locale Route
Route::get('lang/{locale}',[LanguageController::class,'swap']);

app/Http/Controllers/EmployesController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class EmployesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employes = User::all();
  
        return view('pages.employes.index',compact('employes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.employes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'first_name' => 'required',
            'last_name' => 'required',
            'email' => 'required',
        ]);

        $employe = User::create($request->all());
        
        toastr()->success('Employee created successfully');

        return redirect()->route('employes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        $employee = auth()->user();

        return response()->json([
            'data' => $employee
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employe = User::where('id', $id)->first();

        return view('pages.employes.edit',compact('employe'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $employe)
    {
        $request->validate([
            'first_name' => 'required',
            'last_name' => 'required',
            'email' => 'required'
        ]);
  
        $employe->update($request->all());

        toastr()->success('Employee updated successfully');

        return redirect()->route('employes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $employe)
    {
        $employe->delete();
  
        toastr()->success('Employee deleted successfully');

        return redirect()->route('employes.index');
    }

    /**
     * API endpoint to retrieve a user
     *
     * @param  int  $kw
     * @return \Illuminate\Http\Response
     */
    public function search($searchTerm) 
    {
        if( $searchTerm == 'all' ) {
            $employes = User::all();
    
            return response()->json([
                'data' => $employes
            ]);
        }

        $employe = User::query()
                        ->where('first_name', 'LIKE', "%{$searchTerm}%")
                        ->orWhere('last_name', 'LIKE', "%{$searchTerm}%") 
                        ->orWhere('email', 'LIKE', "%{$searchTerm}%") 
                        ->get();

        return response()->json([
            'data' => $employe
        ]);
    }
}

resources/views/pages/employes/create.blade.php
@extends('layouts/contentLayoutMaster', ['sectionIcon' => 'feather icon-briefcase'])

@section('title', 'Créer un nouvel employé')

@section('vendor-style')
        {{-- Page Css files --}}
        <link rel="stylesheet" href="{{ asset(mix('vendors/css/forms/select/select2.min.css')) }}">
@endsection

@section('page-style')
        {{-- Page Css files --}}
        <link rel="stylesheet" href="{{ asset(mix('css/plugins/forms/validation/form-validation.css')) }}">
        <link rel="stylesheet" href="{{ asset(mix('css/pages/employes.css')) }}">
        
@endsection

@section('content')
<!-- Employee edit start -->
<section class="users-edit">
  <div class="card">
    <div class="card-content">
      <div class="card-body">
          <!-- Employee edit account form start -->
          <form novalidate action="{{ route('employes.create') }}" method="POST">
            @csrf
            @method('PUT')
            <div class="row">
              <div class="col-12 col-sm-6">
                <div class="form-group">
                  <div class="controls">
                    <label>Prénom</label>
                    <input type="text" class="form-control" name="first_name" id="first_name" placeholder="Prénom" required
                      data-validation-required-message="This first name field is required">
                  </div>
                </div>
              </div>
              <div class="col-12 col-sm-6">
                <div class="form-group">
                  <div class="controls">
                    <label>Nom</label>
                    <input type="text" class="form-control" name="last_name" id="last_name" placeholder="Nom" required
                      data-validation-required-message="This last name field is required">
                  </div>
                </div>
              </div>
              <div class="col-12 col-sm-6">
                <div class="form-group">
                  <div class="controls">
                    <label>Courriel</label>
                    <input type="text" class="form-control" name="email" id="email" placeholder="Courriel" required
                      data-validation-required-message="This email field is required">
                  </div>
                </div>
              </div>
              <div class="col-12 col-sm-6">
                <div class="form-group">
                  <div class="controls">
                    <label>Adresse</label>
                    <input type="text" class="form-control" name="address" id="address" placeholder="Adresse"">
                  </div>
                </div>
              </div>
              <div class="col-12 col-sm-6">
                <div class="form-group">
                  <div class="controls">
                    <label>Ville</label>
                    <input type="text" class="form-control" name="city" id="city" placeholder="Ville">
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-12">
                <fieldset class="form-group">
                    <label>Province</label>
                    <select class="form-control" name="province">
                        <option>Province</option>
                        <option value="AB">Alberta</option>
                        <option value="BC">British Columbia</option>
                        <option value="MB">Manitoba</option>
                        <option value="NB">New Brunswick</option>
                        <option value="NL">Newfoundland and Labrador</option>
                        <option value="NS">Nova Scotia</option>
                        <option value="ON">Ontario</option>
                        <option value="PE">Prince Edward Island</option>
                        <option value="QC" selected>Quebec</option>
                        <option value="SK">Saskatchewan</option>
                        <option value="NT">Northwest Territories</option>
                        <option value="NU">Nunavut</option>
                        <option value="YT">Yukon</option>
                    </select>
                </fieldset>
            </div>
            <div class="col-md-6 col-12">
                <fieldset class="form-group">
                    <select class="form-control" name="country">
                        <option>Pays</option>
                        <option value="Canada">Canada</option>
                    </select>
                </fieldset>
            </div>
              <div class="col-12 col-sm-6">
                <div class="form-group">
                  <div class="controls">
                    <label>Code postal</label>
                    <input type="text" class="form-control" name="postal_code" id="postal_code" placeholder="Code postal">
                  </div>
                </div>
              </div>
              <div class="col-12 col-sm-6">
                <div class="form-group">
                  <div class="controls">
                    <label>Cellulaire</label>
                    <input type="text" class="form-control" name="mobile" id="mobile" placeholder="Cellulaire">
                  </div>
                </div>
              </div>
              <div class="col-12 col-sm-6">
                <div class="form-group">
                  <label>Type d'employé</label>
                  <select class="form-control" name="level_id">
                    <option value="1" checked>Niveau 1 - Accès spécifique</option>
                    <option value="2">Niveau 2 - Accès standard</option>
                    <option value="3">Niveau 3 - Accès administrateur</option>
                  </select>
                </div>
              </div>
              <div class="col-12 d-flex flex-sm-row flex-column justify-content-end mt-1">
                <button type="submit" class="btn btn-primary glow mb-1 mb-sm-0 mr-0 mr-sm-1">Sauvegarder</button>
              </div>
            </div>
          </form>
          <!-- Clients edit account form ends -->
      </div>
    </div>
  </div>
</section>
<!-- Clients edit ends -->
@endsection

@section('vendor-script')
  {{-- Vendor js files --}}
  <script src="{{ asset(mix('vendors/js/forms/select/select2.full.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/forms/validation/jqBootstrapValidation.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/forms/repeater/jquery.repeater.min.js')) }}"></script>
@endsection

@section('page-script')
  {{-- Page js files --}}
  <script src="{{ asset(mix('js/scripts/pages/employes.js')) }}"></script>
  <script src="{{ asset(mix('js/scripts/navs/navs.js')) }}"></script>
@endsection

resources/views/pages/employes/edit.blade.php
@extends('layouts/contentLayoutMaster', ['sectionIcon' => 'feather icon-briefcase'])

@section('title', 'Edit ' . $employe->first_name . ' ' . $employe->last_name)

@section('vendor-style')
        {{-- Page Css files --}}
        <link rel="stylesheet" href="{{ asset(mix('vendors/css/forms/select/select2.min.css')) }}">
@endsection

@section('page-style')
        {{-- Page Css files --}}
        <link rel="stylesheet" href="{{ asset(mix('css/plugins/forms/validation/form-validation.css')) }}">
        <link rel="stylesheet" href="{{ asset(mix('css/pages/employes.css')) }}">
        
@endsection

@section('content')
<!-- Employee edit start -->
<section class="users-edit">
  <div class="card">
    <div class="card-content">
      <div class="card-body">
          <!-- Employee edit account form start -->
          <form novalidate action="{{ route('employes.update', $employe) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="row">
              <div class="col-12 col-sm-6">
                <div class="form-group">
                  <div class="controls">
                    <label>Prénom</label>
                    <input type="text" class="form-control" name="first_name" id="first_name" placeholder="Prénom" value="{{ $employe->first_name }}" required
                      data-validation-required-message="This first name field is required">
                  </div>
                </div>
              </div>
              <div class="col-12 col-sm-6">
                <div class="form-group">
                  <div class="controls">
                    <label>Nom</label>
                    <input type="text" class="form-control" name="last_name" id="last_name" placeholder="Nom" value="{{ $employe->last_name }}" required
                      data-validation-required-message="This last name field is required">
                  </div>
                </div>
              </div>
              <div class="col-12 col-sm-6">
                <div class="form-group">
                  <div class="controls">
                    <label>Courriel</label>
                    <input type="text" class="form-control" name="email" id="email" placeholder="Courriel" value="{{ $employe->email }}" required
                      data-validation-required-message="This email field is required">
                  </div>
                </div>
              </div>
              <div class="col-12 col-sm-6">
                <div class="form-group">
                  <div class="controls">
                    <label>Adresse</label>
                    <input type="text" class="form-control" name="address" id="address" placeholder="Adresse" value="{{ $employe->address }}">
                  </div>
                </div>
              </div>
              <div class="col-12 col-sm-6">
                <div class="form-group">
                  <div class="controls">
                    <label>Ville</label>
                    <input type="text" class="form-control" name="city" id="city" placeholder="Ville" value="{{ $employe->city }}">
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-12">
                <fieldset class="form-group">
                    <label>Province</label>
                    <select class="form-control" name="province">
                        <option>Province</option>
                        <option value="AB" {{ $employe->province == 'AB' ? ' selected' : '' }}>Alberta</option>
                        <option value="BC" {{ $employe->province == 'BC' ? ' selected' : '' }}>British Columbia</option>
                        <option value="MB" {{ $employe->province == 'MB' ? ' selected' : '' }}>Manitoba</option>
                        <option value="NB" {{ $employe->province == 'NB' ? ' selected' : '' }}>New Brunswick</option>
                        <option value="NL" {{ $employe->province == 'NL' ? ' selected' : '' }}>Newfoundland and Labrador</option>
                        <option value="NS" {{ $employe->province == 'NS' ? ' selected' : '' }}>Nova Scotia</option>
                        <option value="ON" {{ $employe->province == 'ON' ? ' selected' : '' }}>Ontario</option>
                        <option value="PE" {{ $employe->province == 'PE' ? ' selected' : '' }}>Prince Edward Island</option>
                        <option value="QC" {{ $employe->province == 'QC' ? ' selected' : '' }}>Quebec</option>
                        <option value="SK" {{ $employe->province == 'SK' ? ' selected' : '' }}>Saskatchewan</option>
                        <option value="NT" {{ $employe->province == 'NT' ? ' selected' : '' }}>Northwest Territories</option>
                        <option value="NU" {{ $employe->province == 'NU' ? ' selected' : '' }}>Nunavut</option>
                        <option value="YT" {{ $employe->province == 'YT' ? ' selected' : '' }}>Yukon</option>
                    </select>
                </fieldset>
            </div>
            <div class="col-md-6 col-12">
                <fieldset class="form-group">
                  <label>Pays</label>
                    <select class="form-control" name="country" value="{{ $employe->country }}">
                        <option>Pays</option>
                        <option value="Canada">Canada</option>
                    </select>
                </fieldset>
            </div>
              <div class="col-12 col-sm-6">
                <div class="form-group">
                  <div class="controls">
                    <label>Code postal</label>
                    <input type="text" class="form-control" name="postal_code" id="postal_code" placeholder="Code postal" value="{{ $employe->postal_code }}">
                  </div>
                </div>
              </div>
              <div class="col-12 col-sm-6">
                <div class="form-group">
                  <div class="controls">
                    <label>Cellulaire</label>
                    <input type="text" class="form-control" name="mobile" id="mobile" placeholder="Cellulaire" value="{{ $employe->mobile }}">
                  </div>
                </div>
              </div>
              <div class="col-12 col-sm-6">
                <div class="form-group">
                  <label>Type d'employé</label>
                  <select class="form-control" name="level_id">
                    <option value="1" {{ $employe->level_id == '1' ? ' checked' : ''  }}>Niveau 1 - Accès spécifique</option>
                    <option value="2"{{ $employe->level_id == '2' ? ' checked' : ''  }}>Niveau 2 - Accès standard</option>
                    <option value="3"{{ $employe->level_id == '3' ? ' checked' : ''  }}>Niveau 3 - Accès administrateur</option>
                  </select>
                </div>
              </div>
              <div class="col-12 d-flex flex-sm-row flex-column justify-content-end mt-1">
                <button type="submit" class="btn btn-primary glow mb-1 mb-sm-0 mr-0 mr-sm-1">Sauvegarder</button>
              </div>
            </div>
          </form>
          <!-- Clients edit account form ends -->
      </div>
    </div>
  </div>
</section>
<!-- Clients edit ends -->
@endsection

@section('vendor-script')
  {{-- Vendor js files --}}
  <script src="{{ asset(mix('vendors/js/forms/select/select2.full.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/forms/validation/jqBootstrapValidation.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/forms/repeater/jquery.repeater.min.js')) }}"></script>
@endsection

@section('page-script')
  {{-- Page js files --}}
  <script src="{{ asset(mix('js/scripts/pages/employes.js')) }}"></script>
  <script src="{{ asset(mix('js/scripts/navs/navs.js')) }}"></script>
@endsection

resources/views/pages/employes/index.blade.php
@extends('layouts/contentLayoutMaster', ['sectionIcon' => 'feather icon-briefcase'])

@section('title', 'Employes')

@section('vendor-style')
        {{-- vendor css files --}}
        <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/datatables.min.css')) }}">
        @toastr_css
@endsection

@section('content')
<div class="row mb-1">
    <div class="col-12">
        Liste d'employés <a href="{{ route('employes.create') }}" class="btn btn-primary glow mb-1 mb-sm-0 mr-0 mr-sm-1 ml-2">Créer un employé</a>
    </div>
  </div>
  <!-- table -->
  <section id="basic-datatable">
      <div class="row">
          <div class="col-12">
              <div class="card">
                  <div class="card-content">
                      <div class="card-body card-dashboard">
                          <div class="table-responsive">
                              <table class="table zero-configuration">
                                  <thead>
                                      <tr>
                                          <th>Employé</th>
                                          <th>Courriel</th>
                                          <th>Cellulaire</th>
                                          <th>Modifié le</th>
                                          <th>Options</th>
                                      </tr>
                                  </thead>
                                  <tbody>
                                  	@foreach($employes as $employe)
                                      <tr>
                                          <td>
                                              <span class="avatar"><img src="images/portrait/small/{{ $employe->avatar ?? 'avatar.jpg' }}" height="32" width="32"></span>
                                            {{ $employe->first_name }} {{ $employe->last_name }}
                                        </td>
                                          <td>{{ $employe->email }}</td>
                                          <td>{{ $employe->mobile }}</td>
                                          <td>{{ $employe->created }}</td>
                                          <td>
                                              <a href="{{ route('employes.edit', $employe) }}"><i class="users-edit-icon feather icon-edit-1 mr-50"></i></a>
                                              <a href="{{ route('employes.destroy', $employe) }}"><i class="users-delete-icon feather icon-trash-2"></i></a>
                                          </td>
                                      </tr>
                                     @endforeach
                                  </tbody>
                              </table>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <!--/ table -->
  
@endsection
@section('vendor-script')
{{-- vendor files --}}
    <script src="{{ asset(mix('vendors/js/tables/datatable/pdfmake.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/vfs_fonts.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.buttons.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.html5.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.print.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.bootstrap.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.bootstrap4.min.js')) }}"></script>
@endsection
@section('page-script')
    {{-- Page js files --}}
    <script src="{{ asset(mix('js/scripts/datatables/datatable.js')) }}"></script>
    @toastr_js
    @toastr_render
@endsection