routes/web.php
<?php
  use App\Http\Controllers\LanguageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('auth/google', 'Auth\GoogleController@redirectToGoogle');
Route::get('auth/google/callback', 'Auth\GoogleController@handleGoogleCallback');

// Route url
Route::get('/', 'DashboardController@dashboardAnalytics')->name('home')->middleware('auth');
Route::get('/home', 'DashboardController@dashboardAnalytics')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
  // Route Dashboards
  Route::get('/dashboard-analytics', 'DashboardController@dashboardAnalytics');

  // Content resources
  Route::get('/soumissions', 'QuotesController@list');
  Route::get('/soumissions/create', 'QuotesController@create')->name('quotes.create');
  Route::get('/soumissions/{id}/edit', 'QuotesController@edit')->name('quotes.edit');
  Route::get('/soumissions/{id}/delete', 'QuotesController@destroy')->name('quotes.destroy');
  Route::resource('clients','ClientsController');
  Route::resource('employes','EmployesController');

  // Order resources
  Route::get('/commandes', 'OrdersController@index');
  Route::get('/commandes/{order}/edit', 'OrdersController@edit')->name('orders.edit');
  Route::get('/commandes/{order}/delete', 'OrdersController@destroy')->name('orders.destroy');
});

// locale Route
Route::get('lang/{locale}',[LanguageController::class,'swap']);

app/Client.php
<?php

namespace App;

use App\Processors\AvatarProcessor;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $appends = [
        'created',
        'title'
    ];

    protected $hidden = [
        'created_at',
        'updated_at',
        'file_id',
        'file'
    ];

    protected $fillable = [
        'entreprise',
        'is_active',
        'client_type_id',
        'employe_id',
        'notes',
        'file_id'
    ];

    public function contacts() {
        return $this->hasMany('App\Contact');
    }

    public function defaultContact() {
        return $this->contacts()->where('is_default', '0')->first();
    }

    public function addresses() {
        return $this->hasMany('App\Address', 'fk_client_id');
    }

    public function defaultAddress() {
        return $this->addresses()->where('is_default_facturation', '1')->first();
    }

    public function permissions() {
        return $this->belongsToMany('App\User', 'employee_clients', 'fk_client_id', 'fk_employee_id');
    }

    public function file() {
        return $this->belongsTo(File::class);
    }

    public function getAvatarFilenameAttribute() {
        if (!empty($this->file)) {
            return $this->file->name;
        }

        return null;
    }

    public function getAvatarAttribute() {
        return AvatarProcessor::get($this);
    }

    public function getCreatedAttribute() {
        if (empty($this->created_at)) {
            return null;
        }

        return $this->created_at->toFormattedDateString();
    }

    public function getTitleAttribute() {
        return $this->entreprise;
    }

    public function getCreatedMmDdYyyyAttribute() {
        if (empty($this->created_at)) {
            return null;
        }

        return $this->created_at->format('m-d-Y');
    }

    public function setCreatedDateAttribute( $value ) {
        try {
            $this->attributes['created_at'] = new Carbon($value);
        } catch (\Exception $exception) {
            $this->attributes['created_at'] = now();
        }
    }
}

app/Http/Controllers/ClientsController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\User;
use App\Client;
use App\Contact;
use App\Address;
use Illuminate\Http\Request;

class ClientsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::take('20')->get();
  
        return view('pages.clients.index', compact('clients'));
    }
   
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $employes = User::all();

        return view('pages.clients.create')->with('employes', $employes);
    }
  
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'entreprise' => 'required',
            'client_type_id' => 'required',
        ]);

        $request->fk_created_by_id = Auth::id();
  
        $client = Client::create($request->all());

        if($request->contacts) {
            foreach($request->contacts as $contact) {
                $client->contacts()->create($contact);
            }
        }

        if($request->addresses) {
            foreach($request->addresses as $address) {
                $client->addresses()->create($address);
            }
        }

        if($request->permissions) {
            foreach($request->permissions as $permission) {
                $user = User::where('id', $permission)->first();
                $client->permissions()->attach($user);
            }
        }
   
        toastr()->success('Client created successfully');

        return redirect()->route('clients.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function storeClient(Request $request)
    {
        $request->validate([
            'entreprise' => 'required',
            'client_type_id' => 'required',
        ]);
  
        $client = Client::create($request->all());

        return response()->json([
            'code' => 200, 
            'msg' => "Client created!",
            'data' => $client
        ]);
    }
   
    /**
     * Display the specified resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        $client = Client::where('id', $request->id)
                        ->with('addresses')
                        ->with('contacts')
                        ->first();

        return response()->json([
            'data' => $client
        ]);
    }

    /**
     * Display the searched resource(s).
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $client = Client::query()
                        ->where('entreprise', 'LIKE', "%{$request->q}%")
                        ->with('addresses')
                        ->with('contacts')
                        ->get();

        return response()->json([
            'data' => $client
        ]);
    }

    /**
     * Display the searched resource(s).
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function searchAddress(Request $request)
    {
        $client = Address::query()
                        ->where('address', 'LIKE', "%{$request->q}%")
                        ->get();

        return response()->json([
            'data' => $client
        ]);
    }
   
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        $client->load('contacts');
        $client->load('addresses');

        $employes = User::all();

        return view('pages.clients.edit',compact('client'))->with('employes', $employes);
    }
  
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        $request->validate([
            'entreprise' => 'required',
            'client_type_id' => 'required',
        ]);
  
        $client->update($request->all());

        if($request->contacts) {
            foreach($request->contacts as $contact) {
                if(isset($contact['id'])) {
                    $client->contacts()->where('id', $contact['id'])->update($contact);
                } else {
                    $client->employee_id = Auth::id();
                    $client->contacts()->create($contact);
                }
            }
        }

        if($request->address) {
            foreach($request->addresses as $address) {
                if(isset($address['id'])) {
                    $client->addresses()->where('id', $address['id'])->update($address);
                } else {
                    $client->employee_id = Auth::id();
                    $client->addresses()->create($address);
                }
            }
        }

        if($request->permissions) {
            foreach($request->permissions as $permission) {
                $user = User::where('id', $permission)->first();
                $client->permissions()->attach($user);
            }
        }

        toastr()->success('Client updated successfully');

        return redirect()->route('clients.index');
    }
  
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $Client)
    {
        $Client->delete();
  
        toastr()->success('Client deleted successfully');

        return redirect()->route('clients.index');
    }

    public function storeContact(Request $request)
    {
        if( $request->fk_client_id ) {
            $client = Client::where('id', $request->fk_client_id);
            $contact = $client->contacts()->create($request);
        } else {
            $lastClientId = Client::orderBy('id', 'DESC')->first()->pluck('id');
            $request->fk_client_id = $lastClientId ++;
            $contact = Contact::create($request->all());
        }

        $contactId = $contact->id;

        return response()->json([
            'data' => $contactId,
        ]);
    }
}

resources/views/pages/clients/create.blade.php
@extends('layouts/contentLayoutMaster', ['sectionIcon' => 'feather icon-users'])

@section('title', 'New client')

@section('vendor-style')
        {{-- Page Css files --}}
        <link rel="stylesheet" href="{{ asset(mix('vendors/css/forms/select/select2.min.css')) }}">
@endsection

@section('page-style')
        {{-- Page Css files --}}
        <link rel="stylesheet" href="{{ asset(mix('css/plugins/forms/validation/form-validation.css')) }}">
        <link rel="stylesheet" href="{{ asset(mix('css/pages/clients.css')) }}">
        
@endsection

@section('content')
<!-- Client edit start -->
<section class="users-edit">
  <div class="card">
    <div class="card-content">
      <div class="card-body">
          <!-- Client edit account form start -->
          <form novalidate action="{{ route('clients.store') }}" method="POST">
            @csrf
            @method('POST')
            <div class="row">
              <div class="col-12 col-sm-6">
                <div class="form-group">
                  <div class="controls">
                    <label>Nom de l'entreprise</label>
                    <input type="text" class="form-control" name="entreprise" id="entreprise" placeholder="Nom de l'entreprise" required
                      data-validation-required-message="This username field is required">
                  </div>
                </div>
              </div>
              <div class="col-12 col-sm-6">
                <div class="form-group">
                  <label>Type d'entreprise</label>
                  <select class="form-control" name="client_type_id">
                    <option value="1">Particulier</option>
                    <option value="2">Entreprise</option>
                    <option value="3">Gouvernement</option>
                  </select>
                </div>
              </div>
              <div class="col-12">
                <label>Notes</label>
                <fieldset class="form-group">
                    <textarea class="form-control" id="notes"name="notes" rows="3" placeholder="Notes"></textarea>
                </fieldset>
              </div>
            </div>        
            <div class="row">
              <div class="col-12">
                  <h6 class="py-1 mx-1 mb-0 font-medium-2">
                    <i class="feather icon-home mr-50"></i>Adresses
                  </h6>
                  <div id="addresses">
                      <div class="address-entry inline-form row border rounded px-1 py-1 mb-1">
                          <div class="col-12 col-md-6">
                              <input class="form-control mb-1" name="addresses[0][address]" type="text" placeholder="Adresse" />
                          </div>
                          <div class="col-md-6 col-12">
                              <input class="form-control mb-1" name="addresses[0][city]" type="text" placeholder="Ville" />
                          </div>
                          <div class="col-md-6 col-12">
                              <fieldset class="form-group">
                                  <select class="form-control" name="addresses[0][province]">
                                      <option>Province</option>
                                      <option value="AB">Alberta</option>
                                      <option value="BC">British Columbia</option>
                                      <option value="MB">Manitoba</option>
                                      <option value="NB">New Brunswick</option>
                                      <option value="NL">Newfoundland and Labrador</option>
                                      <option value="NS">Nova Scotia</option>
                                      <option value="ON">Ontario</option>
                                      <option value="PE">Prince Edward Island</option>
                                      <option value="QC">Quebec</option>
                                      <option value="SK">Saskatchewan</option>
                                      <option value="NT">Northwest Territories</option>
                                      <option value="NU">Nunavut</option>
                                      <option value="YT">Yukon</option>
                                  </select>
                              </fieldset>
                          </div>
                          <div class="col-md-6 col-12">
                              <fieldset class="form-group">
                                  <select class="form-control" name="addresses[0][country]">
                                      <option>Pays</option>
                                      <option value="Canada">Canada</option>
                                  </select>
                              </fieldset>
                          </div>
                          <div class="col-md-6 col-12">
                              <input class="form-control mb-1" name="addresses[0][postal_code]" type="text" placeholder="Code postal" />
                          </div>
                          <div class="col-md-6 col-12">
                            <ul class="list-unstyled mb-0">
                              <li class="d-inline-block mr-2">
                              <fieldset >
                                <label>
                                  <input type="checkbox" name="addresses[0][is_default_facturation]" value="1">
                                  Facturation
                                </label>
                              </fieldset>
                            </li>
                            <li class="d-inline-block mr-2">
                              <fieldset>
                                <label>
                                  <input type="checkbox" name="addresses[0][is_default_shipping]" value="1">
                                  Livraison
                                </label>
                              </fieldset>
                            </li>
                          </ul>
                          </div>
                          <div class="col-12 text-right">
                              <button type="button" class="btn btn-success btn-sm btn-add-address">
                                  <i class="feather icon-plus"></i>
                              </button>
                          </div>
                      </div>
                  </div>
              </div>
              <div class="col-12">
                  <h6 class="py-1 mx-1 mb-0 font-medium-2">
                    <i class="feather icon-user mr-50"></i>Contacts
                  </h6>
                  <div id="contacts">
                      <div class="contact-entry inline-form row border rounded px-1 py-1 mb-1">
                          <div class="col-12 col-md-6">
                              <input class="form-control mb-1" name="contacts[0][first_name]" type="text" placeholder="Prénom" />
                          </div>
                          <div class="col-md-6 col-12">
                              <input class="form-control mb-1" name="contacts[0][last_name]" type="text" placeholder="Nom" />
                          </div>
                          <div class="col-md-6 col-12">
                              <input class="form-control mb-1" name="contacts[0][email]" type="text" placeholder="Courriel" />
                          </div>
                          <div class="col-md-6 col-12">
                              <input class="form-control mb-1" name="contacts[0][phone]" type="text" placeholder="Téléphone" />
                          </div>
                          <div class="col-md-6 col-12">
                              <input class="form-control mb-1" name="contacts[0][cell]" type="text" placeholder="Cellulaire" />
                          </div>
                          <div class="col-12 text-right">
                              <button type="button" class="btn btn-success btn-sm btn-add-contact">
                                  <i class="feather icon-plus"></i>
                              </button>
                          </div>
                      </div>
                  </div>
              </div>
              <div class="col-12">
                  <h6 class="py-1 mx-1 mb-0 font-medium-2">
                    <i class="feather icon-lock mr-50"></i>Permissions
                  </h6>
                  Ce client peut être vu par les administrateurs et par: 
                  
                  <div class="form-group">
                    <select class="select2 form-control" multiple="multiple" name="permissions[]" id="permissions-select2">
                      @foreach($employes as $employe)
                      <option value="{{ $employe->id }}">{{ $employe->first_name }} {{ $employe->last_name }}</option>
                      @endforeach
                    </select>
                  </div>
              </div>
              <div class="col-12 d-flex flex-sm-row flex-column justify-content-end mt-1">
                <button type="submit" class="btn btn-primary glow mb-1 mb-sm-0 mr-0 mr-sm-1">Sauvegarder</button>
              </div>
            </div>
          </form>
          <!-- Clients edit account form ends -->
      </div>
    </div>
  </div>
</section>
<!-- Clients edit ends -->
@endsection

@section('vendor-script')
  {{-- Vendor js files --}}
  <script src="{{ asset(mix('vendors/js/forms/select/select2.full.min.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/forms/validation/jqBootstrapValidation.js')) }}"></script>
  <script src="{{ asset(mix('vendors/js/forms/repeater/jquery.repeater.min.js')) }}"></script>
@endsection

@section('page-script')
  {{-- Page js files --}}
  <script src="{{ asset(mix('js/scripts/pages/clients.js')) }}"></script>
  <script src="{{ asset(mix('js/scripts/navs/navs.js')) }}"></script>
@endsection

resources/views/pages/clients/index.blade.php
@extends('layouts/contentLayoutMaster', ['sectionIcon' => 'feather icon-users'])

@section('title', 'Clients')

@section('vendor-style')
        {{-- vendor css files --}}
        <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/datatables.min.css')) }}">
@endsection

@section('content')
<div class="row mb-1">
    <div class="col-12">
        Liste de clients <a href="{{ route('clients.create') }}" class="btn btn-primary glow mb-1 mb-sm-0 mr-0 mr-sm-1 ml-2">Créer un client</a>
    </div>
  </div>
  <!-- table -->
  <section id="basic-datatable">
      <div class="row">
          <div class="col-12">
              <div class="card">
                  <div class="card-content">
                      <div class="card-body card-dashboard">
                          <div class="table-responsive">
                              <table class="table zero-configuration">
                                  <thead>
                                      <tr>
                                          <th>Client</th>
                                          <th>Type</th>
                                          <td>Contact (courriel)</td>
                                          <th>Contact (tel)</th>
                                          <th>Code postal</th>
                                          <th>Province</th>
                                          <th>Représentant</th>
                                          <th>Crée le</th>
                                          <th>Modifié le</th>
                                          <th>Options</th>
                                      </tr>
                                  </thead>
                                  <tbody>
                                      @foreach($clients as $client)
                                      <tr>
                                          <td>{{ $client->entreprise }}</td>
                                          <td>{{ $client->client_type_id }}</td>
                                          <td>{{ $client->defaultContact()['email'] }}</td>
                                          <td>{{ $client->defaultContact()['phone'] }}</td>
                                          <td>{{ $client->defaultAddress()['postal_code'] }}</td>
                                          <td>{{ $client->defaultAddress()['province'] }}</td>
                                          <td>{{ $client->employee_id }}</td>
                                          <td>{{ $client->created_at }}</td>
                                          <td>{{ $client->updated_at }}</td>
                                          <td>
                                              <a href="{{ route('clients.edit', $client) }}"><i class="users-edit-icon feather icon-edit-1 mr-50"></i></a>
                                              <a href="{{ route('clients.destroy', $client) }}"><i class="users-delete-icon feather icon-trash-2"></i></a>
                                          </td>
                                      </tr>
                                     @endforeach
                                  </tbody>
                              </table>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <!--/ table -->
  
@endsection
@section('vendor-script')
{{-- vendor files --}}
        <script src="{{ asset(mix('vendors/js/tables/datatable/pdfmake.min.js')) }}"></script>
        <script src="{{ asset(mix('vendors/js/tables/datatable/vfs_fonts.js')) }}"></script>
        <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.min.js')) }}"></script>
        <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.buttons.min.js')) }}"></script>
        <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.html5.min.js')) }}"></script>
        <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.print.min.js')) }}"></script>
        <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.bootstrap.min.js')) }}"></script>
        <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.bootstrap4.min.js')) }}"></script>
@endsection
@section('page-script')
        {{-- Page js files --}}
        <script src="{{ asset(mix('js/scripts/datatables/datatable.js')) }}"></script>
@endsection